name:        chessIO
version:     0.3.0.0
github:      "mlang/chessIO"
license:     BSD3
author:      "Mario Lang"
maintainer:  "mlang@blind.guru"
copyright:   "2019 Mario Lang"

synopsis:    Basic chess move generation and UCI client library
category:    Game
description: A simple library for generating legal chess moves.
  Also includes a module for communication with external processes that
  speak the UCI (Universal Chess Interface) protocol.
  On top of that, provides a console frontend program (cboard) that can be used
  to interactively play against UCI engines.

dependencies:
- attoparsec
- base >= 4.8 && < 5
- bytestring
- megaparsec
- parser-combinators
- process
- stm
- unordered-containers
- vector

default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- DeriveGeneric
- LambdaCase
- NamedFieldPuns
- NumericUnderscores
- RecordWildCards
- OverloadedStrings
- TupleSections
- ViewPatterns

extra-source-files:
- README.rst

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src
  exposed-modules:
  - Game.Chess
  - Game.Chess.UCI

executables:
  cboard:
    main:                cboard.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    dependencies:
    - chessIO
    - haskeline
    - mtl
    - split

tests:
  perft:
    main:                Perft.hs
    source-dirs:  test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -s"
    dependencies:
    - chessIO
    - directory
    - parallel
    - time
